### ISSUE TITLE
Code outdated and not working with recent versions of Pandas (v1.0.1) anymore

### ISSUE THREAD

**Issue by ChristophWiesmeyr** [liuyigh/PyHRM#2]
I noticed that in several places the code does not work anymore with recent versions of Pandas. I made the necessary changes to make it work again. If you make me a collaborator, I am happy to share the code in a new branch. Alternatively, I can also send the code by email.

**Comment by liuyigh** [comment]
I don't know how to do collaborator. And I know how to do pull requests. Thanks!

**Comment by ChristophWiesmeyr** [comment]
Hm, I am also not too experienced with github. The problem is that I cannot
access the repository and therefore I cannot create a branch to send you a
pull request.

I think this would be the way to go to make me a collaborator:
https://help.github.jp/enterprise/2.11/user/articles/inviting-collaborators-to-a-personal-repository/

If it is easier for you, I can also just send you the code directly via
email.

Best, Christoph

Am Mo., 6. Juli 2020 um 09:37 Uhr schrieb Yi Liu <notifications@github.com>:

**Comment by liuyigh** [comment]
Dear Christoph,

Actually I tried that before, no such option in my interface. What other users did before was fork the repo then submit a pull request.

I think that is what they do for most repos on github. Collaborators are more like for a real team.

Best, Yi

**Comment by ChristophWiesmeyr** [comment]
dear yi, seems like that is the standard workflow on github. i will send
you a pull request when i am back from my holidays.

best, christooh

Yi Liu <notifications@github.com> schrieb am Mo., 6. Juli 2020, 21:42:

**Comment by liuyigh** [comment]
Thanks, Chris! Looking forward to your contribution. And enjoy your holidays!

Best, Yi

**Comment by liuyigh** [comment]
I have just updated the code for pandas 1.0. https://github.com/liuyigh/PyHRM/commit/ca69526cc3c34cd744854f94aca12e6f30c4e141

Closing this issue. Thanks, again~
