### ISSUE TITLE
First derivative calculation

### ISSUE THREAD

**Issue by areyesromero** [liuyigh/PyHRM#4]
Hello Yi Liu, 
I was using your Python script to calculate the melting temperature from a DSF experiment.
Tm can be estimated from the point of maximum slope or inflection point: I think if the script could implement this possibility it would be useful. What do you think? In principle in order to calculate the position of the inflection point you can calculate the first derivative of the unfolding trace (dFI/dT vs. T) and locate the maximum. Any idea how to do it?
Bests
Atilio

**Comment by liuyigh** [comment]
Hi, Atilio,

I have added this to latest pyHRM.py
```
# ### Melting temp

dfdt = df_norm.diff()
plt.plot(df_melt.iloc[:,[0]],dfdt)
plt.show()

dfdtWithTemp = pd.concat([df_melt.iloc[:,[0]],dfdt],axis=1)
meltTempList = dfdtWithTemp.set_index('Temperature').idxmin()
```
